---
version: "2.0"
services:
  ${SNAPSHOT_SVC}:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
        accept:
          - statesync.terp.network # ← only for RPC, not P2P
    env:
      - MONIKER=${SNAPSHOT_MONIKER}
      - CHAIN_JSON=${CHAIN_JSON}
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - PRUNING=nothing
      - STATESYNC_SNAPSHOT_INTERVAL=500
      # - COSMOVISOR_ENABLED=1
      - TERPD_P2P_PEX=false
      - ADDRBOOK_URL=${ADDRBOOK_URL}
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - WASMVM_PATH=/lib/libwasmvm.x86_64.so
      - WASMVM_VERSION=v3.0.2
      - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v3.0.2/libwasmvm.x86_64.so
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - S3_HOST=${S3_HOST}
      - SNAPSHOT_URL=${SNAPSHOT_URL}
      - SNAPSHOT_FORMAT=tar.lz4
      - SNAPSHOT_PATH=${SNAPSHOT_PATH}
      - SNAPSHOT_TIME=${SNAPSHOT_TIME}
      - SNAPSHOT_DIR=/root/.terpd
      - SNAPSHOT_METADATA=1
      - SNAPSHOT_METADATA_URL=${SNAPSHOT_METADATA_URL}
      - SNAPSHOT_SAVE_FORMAT=${SNAPSHOT_SAVE_FORMAT}
      - SNAPSHOT_RETAIN=${SNAPSHOT_RETAIN}
      - SNAPSHOT_KEEP_LAST=${SNAPSHOT_KEEP_LAST}
      - SNAPSHOT_ON_START=1
      - TLS_CONFIG_URL=${TLS_CONFIG_URL}
      - RPC_DOMAIN=statesync.terp.network
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    command:
      - sh
    args:
      - -c
      - curl -fsSL ${ENTRYPOINT_URL} -o /tmp/wrapper.sh; sh /tmp/wrapper.sh
  ${SEED_SVC}:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: 26657
        as: 26657
        accept:
          - seed-statesync.terp.network
          - www.seed-statesync.terp.network
        to:
          - global: true
      - port: 26656
        as: 26656
        accept:
          - seed.terp.network
          - www.seed.terp.network
        to:
          - global: true
    env:
      - TLS_CONFIG_URL=${TLS_CONFIG_URL}
      - MONIKER=${SEED_MONIKER}
      - CHAIN_JSON=${CHAIN_JSON}
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      - TERPD_P2P_PEX=true
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - WASMVM_PATH=/lib/libwasmvm.x86_64.so
      - WASMVM_VERSION=v3.0.2
      - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v3.0.2/libwasmvm.x86_64.so
      # - COSMOVISOR_ENABLED=1
      # - STATESYNC_RPC_SERVERS=<mainnet-terp-rpc.konsortech.xyz:443,rpc.terp.aknodes.net:443>
      - ADDRBOOK_URL=${ADDRBOOK_URL}
      - SNAPSHOT_URL=${SNAPSHOT_URL}
      - SNAPSHOT_FORMAT=tar.lz4
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - RPC_DOMAIN=seed.terp.network
    command:
      - sh
    args:
      - -c
      - curl -fsSL ${ENTRYPOINT_URL} -o /tmp/wrapper.sh; sh /tmp/wrapper.sh
  ${MINIO_SVC}:
    image: ${MINIO_IPFS_IMAGE}
    expose:
      - port: 9001
        as: 9001
        to:
          - global: true
      - port: 8081
        as: 8081
        to:
          - global: true
      - port: 9000
        as: 9000
        to:
          - service: ${SNAPSHOT_SVC}
      - port: 80
        as: 80
        to:
          - global: true
        accept:
          - ${SNAPSHOT_DOWNLOAD_DOMAIN}
        http_options:
          max_body_size: 104857600
          read_timeout: 60000
          send_timeout: 60000
      - port: 443
        as: 443
        proto: tcp
        to:
          - global: true
      - port: 4001
        as: 4001
        proto: tcp
        to:
          - global: true
    env:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_CONSOLE_PORT=9001
      - IPFS_GATEWAY_PORT=8081
      - IPFS_PROFILE=server
      - AUTOPIN_INTERVAL=${AUTOPIN_INTERVAL}
      - AUTOPIN_PATTERNS=*.tar.gz,*.tar.zst,*.tar.lz4,*.tar.xz
      - PUID=1000
      - PGID=1000
      - SNAPSHOT_DOWNLOAD_DOMAIN=${SNAPSHOT_DOWNLOAD_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    params:
      storage:
        ipfs-data:
          mount: /data/ipfs
          readOnly: false
        minio-data:
          mount: /data/minio
          readOnly: false
profiles:
  compute:
    ${SNAPSHOT_SVC}:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          - size: 50Gi
    ${SEED_SVC}:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          - size: 50Gi
    ${MINIO_SVC}:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 10Gi
          - name: ipfs-data
            size: 100Gi
            attributes:
              persistent: true
              class: beta3
          - name: minio-data
            size: 50Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      pricing:
        ${SNAPSHOT_SVC}:
          denom: uakt
          amount: 1000
        ${SEED_SVC}:
          denom: uakt
          amount: 1000
        ${MINIO_SVC}:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  ${SNAPSHOT_SVC}:
    dcloud:
      profile: ${SNAPSHOT_SVC}
      count: 1
  ${SEED_SVC}:
    dcloud:
      profile: ${SEED_SVC}
      count: 1
  ${MINIO_SVC}:
    dcloud:
      profile: ${MINIO_SVC}
      count: 1
