#!/usr/bin/env bash
# expose.sh — Manage which oline-server ports are accessible via SSH tunnel.
#
# Two access modes (toggle with restrict / unrestrict):
#
#   unrestricted (default)
#     SOCKS proxy active — client can reach ALL localhost ports.
#     No PermitOpen in sshd. Client tunnel uses DynamicForward.
#
#   restricted
#     Only registered services are forwarded. sshd PermitOpen enforces
#     the allowlist. Client tunnel uses LocalForward (no SOCKS).
#
# Usage (on oline-server / groot):
#   expose unrestrict            # SOCKS mode — all ports (default)
#   expose restrict              # locked-down mode — registered ports only
#   expose add opencode 49976 --desc "OpenCode web UI"
#   expose add grafana   3000 --desc "Grafana dashboard"
#   expose remove opencode
#   expose list                  # human-readable table
#   expose list --json           # machine-readable (for tunnel sync)
#   expose status                # show mode + registry + port health
#   expose apply                 # re-apply current mode to sshd
#
# Environment:
#   EXPOSE_DB    — service registry path   [~/.oline/services]
#   SSHD_CONF    — sshd_config.d include   [/etc/ssh/sshd_config.d/oline-expose.conf]
#   SSHD_USER    — SSH user to restrict     [$USER]
set -euo pipefail

EXPOSE_DB="${EXPOSE_DB:-$HOME/.oline/services}"
SSHD_CONF="${SSHD_CONF:-/etc/ssh/sshd_config.d/oline-expose.conf}"
SSHD_USER="${SSHD_USER:-$USER}"
MODE_FILE="$(dirname "$EXPOSE_DB")/mode"   # contains "all" or "restricted"

# ── Helpers ───────────────────────────────────────────────────────────────────

die()  { echo "ERROR: $*" >&2; exit 1; }
info() { echo "  $*"; }

ensure_db() {
    mkdir -p "$(dirname "$EXPOSE_DB")"
    [[ -f "$EXPOSE_DB" ]] || touch "$EXPOSE_DB"
}

read_mode() {
    # Returns "all" (default) or "restricted"
    [[ -f "$MODE_FILE" ]] && cat "$MODE_FILE" || echo "all"
}

save_mode() {
    mkdir -p "$(dirname "$MODE_FILE")"
    echo "$1" > "$MODE_FILE"
}

# Read registry lines: skip blank + comment lines.
read_services() {
    grep -v '^[[:space:]]*#' "$EXPOSE_DB" 2>/dev/null | grep -v '^[[:space:]]*$' || true
}

service_exists() {
    local name="$1"
    read_services | awk -v n="$name" '$1 == n { found=1 } END { exit !found }'
}

# ── SSH PermitOpen management ─────────────────────────────────────────────────

# Write (or remove) the PermitOpen rule for $SSHD_USER.
# Requires write access to $SSHD_CONF (typically needs sudo).
# Silently skips if the file cannot be written — registry still updated.
can_write_sshd() {
    local conf_dir
    conf_dir="$(dirname "$SSHD_CONF")"
    if [[ -f "$SSHD_CONF" && -w "$SSHD_CONF" ]] || [[ -w "$conf_dir" ]]; then
        return 0
    fi
    command -v sudo &>/dev/null && sudo -n test -w "$conf_dir" 2>/dev/null
}

sshd_write_cmd() {
    local conf_dir
    conf_dir="$(dirname "$SSHD_CONF")"
    if [[ -w "$conf_dir" ]] || [[ -f "$SSHD_CONF" && -w "$SSHD_CONF" ]]; then
        echo "tee"
    else
        echo "sudo tee"
    fi
}

remove_sshd_conf() {
    [[ -f "$SSHD_CONF" ]] || return 0
    if [[ -w "$SSHD_CONF" ]]; then
        rm -f "$SSHD_CONF"
    else
        sudo rm -f "$SSHD_CONF"
    fi
}

apply_sshd() {
    local mode
    mode=$(read_mode)

    if [[ "$mode" == "all" ]]; then
        # Unrestricted — only need sshd action if a restriction file already exists
        if [[ -f "$SSHD_CONF" ]]; then
            if ! can_write_sshd; then
                echo "  Note: cannot remove ${SSHD_CONF} — run: sudo expose apply"
                return 0
            fi
            remove_sshd_conf
            info "Removed ${SSHD_CONF} — all ports accessible (unrestricted mode)."
            reload_sshd
        fi
        # No file, no action needed — SSH default is already unrestricted
        return 0
    fi

    # Restricted mode — needs write access to create/update the conf
    if ! can_write_sshd; then
        echo "  Note: cannot write ${SSHD_CONF} — SSH enforcement not updated."
        echo "  Run with sudo to enforce access control: sudo expose apply"
        return 0
    fi

    # Restricted mode — build PermitOpen list from registry
    local ports=()
    while IFS=$'\t' read -r _name port _desc; do
        ports+=("127.0.0.1:${port}")
    done < <(read_services)

    if [[ "${#ports[@]}" -eq 0 ]]; then
        info "Warning: restricted mode with no registered services — nothing will be accessible."
        info "Add services first: expose add NAME PORT --desc TEXT"
    fi

    local permit_list="${ports[*]:-}"
    # If no ports registered, use a placeholder that blocks everything
    [[ -z "$permit_list" ]] && permit_list="none"

    $(sshd_write_cmd) "$SSHD_CONF" > /dev/null <<EOF
# oline-managed: do not edit — regenerated by expose.sh
# Restricts SSH tunnel forwards to explicitly registered services only.
# SOCKS proxy (DynamicForward) is blocked server-side.
Match User ${SSHD_USER}
    PermitOpen ${permit_list}
    PermitTunnel no
    GatewayPorts no
EOF

    info "Updated ${SSHD_CONF} — ${#ports[@]} port(s) allowed for ${SSHD_USER}."
    reload_sshd
}

cmd_unrestrict() {
    save_mode "all"
    echo "Mode: unrestricted — SOCKS proxy active, all ports accessible."
    apply_sshd
    echo ""
    echo "  Client: just tunnel sync && just tunnel up"
}

cmd_restrict() {
    save_mode "restricted"
    echo "Mode: restricted — only registered services accessible."
    local count
    count=$(read_services | wc -l | tr -d ' ')
    if [[ "$count" -eq 0 ]]; then
        echo "  Warning: no services registered yet. Run: expose add NAME PORT --desc TEXT"
    else
        echo "  ${count} registered service(s) will be accessible."
    fi
    apply_sshd
    echo ""
    echo "  Client: just tunnel sync && just tunnel up"
}

reload_sshd() {
    local reload_ok=""
    # Try systemctl first (Linux), then launchctl (macOS), then kill -HUP
    if command -v systemctl &>/dev/null && systemctl is-active --quiet sshd 2>/dev/null; then
        if sudo systemctl reload sshd 2>/dev/null || sudo systemctl reload ssh 2>/dev/null; then
            info "sshd reloaded (systemctl)."
            reload_ok=1
        fi
    fi
    if [[ -z "$reload_ok" ]] && pgrep -x sshd &>/dev/null; then
        local sshd_pid
        sshd_pid=$(pgrep -ox sshd | head -1 || true)
        [[ -n "$sshd_pid" ]] && sudo kill -HUP "$sshd_pid" 2>/dev/null && \
            info "sshd reloaded (kill -HUP $sshd_pid)." && reload_ok=1
    fi
    [[ -z "$reload_ok" ]] && info "Note: could not reload sshd automatically. Run: sudo systemctl reload sshd"
}

# ── Commands ──────────────────────────────────────────────────────────────────

cmd_add() {
    local name="${1:?Usage: expose add NAME PORT [--desc TEXT]}"
    local port="${2:?Usage: expose add NAME PORT [--desc TEXT]}"
    shift 2
    local desc="$name"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --desc|-d) desc="$2"; shift 2 ;;
            *) die "Unknown option: $1" ;;
        esac
    done

    [[ "$port" =~ ^[0-9]+$ ]] || die "PORT must be a number, got: $port"
    [[ "$port" -ge 1 && "$port" -le 65535 ]] || die "PORT out of range: $port"

    ensure_db

    # Check for duplicate name or port
    if service_exists "$name"; then
        die "Service '${name}' already registered. Use 'expose remove ${name}' first."
    fi
    local existing_port
    existing_port=$(read_services | awk -v p="$port" '$2 == p { print $1 }' | head -1 || true)
    if [[ -n "$existing_port" ]]; then
        die "Port ${port} already registered as '${existing_port}'."
    fi

    printf '%s\t%s\t%s\n' "$name" "$port" "$desc" >> "$EXPOSE_DB"
    echo "Registered: ${name} → localhost:${port} (${desc})"

    # Check if anything is actually listening on this port
    if command -v ss &>/dev/null; then
        ss -tlnp 2>/dev/null | grep -q ":${port} " && info "Port ${port} is listening." || \
            info "Note: nothing listening on port ${port} yet."
    elif command -v lsof &>/dev/null; then
        lsof -i :"$port" &>/dev/null && info "Port ${port} is listening." || \
            info "Note: nothing listening on port ${port} yet."
    fi

    apply_sshd
}

cmd_remove() {
    local name="${1:?Usage: expose remove NAME}"
    ensure_db
    service_exists "$name" || die "No service named '${name}'. Run 'expose list'."

    # Remove line from registry
    local tmp
    tmp=$(mktemp)
    grep -v "^${name}	" "$EXPOSE_DB" > "$tmp" || true
    mv "$tmp" "$EXPOSE_DB"
    echo "Removed: ${name}"

    apply_sshd
}

cmd_list() {
    local json=""
    [[ "${1:-}" == "--json" ]] && json=1
    ensure_db

    local services
    services=$(read_services)

    if [[ -n "$json" ]]; then
        # Output JSON array for tunnel sync
        echo "["
        local first=1
        while IFS=$'\t' read -r name port desc; do
            [[ -n "$first" ]] || echo ","
            first=""
            printf '  {"name":"%s","port":%s,"desc":"%s"}' \
                "${name}" "${port}" "${desc//\"/\\\"}"
        done <<< "${services:-}"
        echo ""
        echo "]"
        return 0
    fi

    if [[ -z "$services" ]]; then
        echo "No services registered."
        echo "  Add one: expose add opencode 49976 --desc 'OpenCode web UI'"
        return 0
    fi

    printf '%-20s  %-8s  %s\n' "NAME" "PORT" "DESCRIPTION"
    printf '%-20s  %-8s  %s\n' "----" "----" "-----------"
    while IFS=$'\t' read -r name port desc; do
        printf '%-20s  %-8s  %s\n' "$name" "$port" "$desc"
    done <<< "$services"
}

cmd_status() {
    ensure_db

    local mode
    mode=$(read_mode)

    echo "=== Expose Status ==="
    echo ""

    if [[ "$mode" == "all" ]]; then
        echo "  Mode: UNRESTRICTED — SOCKS proxy, all ports accessible"
        echo "        Change: expose restrict"
    else
        echo "  Mode: RESTRICTED — only registered services accessible"
        echo "        Change: expose unrestrict"
    fi

    # sshd enforcement state
    if [[ -f "$SSHD_CONF" ]]; then
        local permit_count
        permit_count=$(grep -c "PermitOpen" "$SSHD_CONF" 2>/dev/null || echo 0)
        if [[ "$permit_count" -gt 0 ]]; then
            echo "  SSH:  PermitOpen ACTIVE (enforced)"
        else
            echo "  SSH:  conf file exists but no PermitOpen found"
        fi
    else
        if [[ "$mode" == "restricted" ]]; then
            echo "  SSH:  not enforced — run: sudo expose apply"
        else
            echo "  SSH:  no restrictions (unrestricted mode)"
        fi
    fi

    echo ""

    local services
    services=$(read_services)

    if [[ -z "$services" ]]; then
        echo "  No services registered."
        if [[ "$mode" == "restricted" ]]; then
            echo "  Add one: expose add opencode 49976 --desc 'OpenCode web UI'"
        fi
    else
        printf '  %-20s  %-8s  %-10s  %s\n' "NAME" "PORT" "LISTENING" "DESCRIPTION"
        printf '  %-20s  %-8s  %-10s  %s\n' "----" "----" "---------" "-----------"
        while IFS=$'\t' read -r name port desc; do
            local listening="no"
            if command -v ss &>/dev/null; then
                ss -tlnp 2>/dev/null | grep -q ":${port} " && listening="yes"
            elif command -v lsof &>/dev/null; then
                lsof -i :"$port" &>/dev/null 2>&1 && listening="yes"
            fi
            printf '  %-20s  %-8s  %-10s  %s\n' "$name" "$port" "$listening" "$desc"
        done <<< "$services"
    fi

    echo ""
    echo "  Registry: ${EXPOSE_DB}"
    [[ -f "$SSHD_CONF" ]] && echo "  SSH conf: ${SSHD_CONF}"
    echo ""
    echo "  Client sync: just tunnel sync  (run on client device after any change)"
}

cmd_apply() {
    ensure_db
    local mode
    mode=$(read_mode)
    echo "==> Applying SSH enforcement (mode: ${mode}) ..."
    apply_sshd
}

# ── Main ──────────────────────────────────────────────────────────────────────

CMD="${1:-help}"
shift 2>/dev/null || true

case "$CMD" in
    unrestrict) cmd_unrestrict ;;
    restrict)   cmd_restrict ;;
    add)        cmd_add "$@" ;;
    remove)     cmd_remove "$@" ;;
    list)       cmd_list "$@" ;;
    status)     cmd_status ;;
    apply)      cmd_apply ;;
    *)
        local mode
        mode=$(read_mode 2>/dev/null || echo "all")
        cat <<EOF
expose.sh — Manage SSH-accessible services on oline-server

Current mode: ${mode}

Access mode:
  unrestrict                    SOCKS proxy — client reaches ALL ports (default)
  restrict                      Locked down — only registered services accessible

Service registry:
  add NAME PORT [--desc TEXT]   Register a service
  remove NAME                   Deregister a service
  list [--json]                 Show registered services
  status                        Show mode + registry + port health

SSH enforcement:
  apply                         Re-apply current mode to sshd (use with sudo)

Workflow:
  # Give access to everything (SOCKS proxy)
  expose unrestrict
  just tunnel sync && just tunnel up

  # Lock down to specific services only
  expose add opencode 49976 --desc "OpenCode web UI"
  expose add grafana   3000 --desc "Grafana dashboard"
  expose restrict              # (sudo for SSH-level enforcement)
  just tunnel sync && just tunnel up

Environment:
  EXPOSE_DB=${EXPOSE_DB}
  SSHD_CONF=${SSHD_CONF}
  SSHD_USER=${SSHD_USER}
EOF
        ;;
esac
