---
version: "2.0"
services:
  oline-a-snapshot:
    image: ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
        accept:
          - statesync-a.terp.network # ← only for RPC, not P2P
    env:
      - MONIKER=terp-node
      - CHAIN_JSON=https://raw.githubusercontent.com/hard-nett/chain-registry-1/refs/heads/v5.0.1/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAPSHOT_INTERVAL=500
      # - COSMOVISOR_ENABLED=1
      # - STATESYNC_RPC_SERVERS=<https://terp.rpc.m.anode.team:443,rpc.terp.aknodes.net:443>
      # - PRUNING=nothing
      # peer exchange disabled
      - TERPD_P2P_PEX=false
      # public address book & snapshot
      - ADDRBOOK_URL=https://raw.githubusercontent.com/111STAVR111/props/main/Terp/addrbook.json
      - SNAPSHOT_URL=https://server-4.itrocket.net/mainnet/terp/terp_2025-10-23_14746539_snap.tar.lz4
      - SNAPSHOT_FORMAT=tar.lz4
      - TERPD_P2P_PRIVATE_PEER_IDS=0a56999f4f22a72234bed90e0beb7dcab26df331@100.16.250.228:26657
      - WASMVM_PATH=/lib/libwasmvm.x86_64.so
      - WASMVM_VERSION=v3.0.2
      - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v3.0.2/libwasmvm.x86_64.so
      # s3 API bucket auth
      # - S3_KEY=
      # - S3_SECRET=
      # - S3_HOST=https://s3.filebase.com
      # - SNAPSHOT_PATH=snapshots/terpnetwork
      # - SNAPSHOT_TIME=22:45:00
      # - SNAPSHOT_SIZE=214748364800
      # - SNAPSHOT_DIR=/root/.terp
      # - SNAPSHOT_METADATA=0
      # - SNAPSHOT_SAVE_FORMAT=tar.gz
  oline-a-seed:
    image: ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
    expose:
      - port: 26657
        as: 26657
        accept:
          - statesync-b.terp.network
          - www.statesync-b.terp.network
        to:
          - global: true
      # DNS for <id>@seed.terp.network:26656
      - port: 26656
        as: 26656
        accept:
          - seed.terp.network
          - www.seed.terp.network
        to:
          - global: true
    env:
      - MONIKER=oline::special::seed-node
      # default chain cfg
      - CHAIN_JSON=https://raw.githubusercontent.com/hard-nett/chain-registry-1/refs/heads/v5.0.1/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      # peer exchange enabled
      - TERPD_P2P_PEX=true
      # public address book & snapshot
      - SNAPSHOT_URL=https://server-4.itrocket.net/mainnet/terp/terp_2025-10-23_14746539_snap.tar.lz4
      - SNAPSHOT_FORMAT=tar.lz4
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAPSHOT_INTERVAL=500
      # - COSMOVISOR_ENABLED=1
      - WASMVM_PATH=/lib/libwasmvm.x86_64.so
      - WASMVM_VERSION=v3.0.2
      - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v3.0.2/libwasmvm.x86_64.so
      # - STATESYNC_RPC_SERVERS=<mainnet-terp-rpc.konsortech.xyz:443,rpc.terp.aknodes.net:443>
      - ADDRBOOK_URL=https://raw.githubusercontent.com/111STAVR111/props/main/Terp/addrbook.json
profiles:
  compute:
    oline-a-snapshot:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 250Gi
    oline-a-seed:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          - size: 50Gi
  placement:
    dcloud:
      pricing:
        oline-a-snapshot:
          denom: uakt
          amount: 1000
        oline-a-seed:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  oline-a-snapshot:
    dcloud:
      profile: oline-a-snapshot
      count: 1
  oline-a-seed:
    dcloud:
      profile: oline-a-seed
      count: 1
