---
version: "2.0"
services:
  oline-b-left-node:
    image: ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
    env:
      - MONIKER=terp-node
      - CHAIN_JSON=https://raw.githubusercontent.com/hard-nett/chain-registry-1/refs/heads/v5.0.1/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      # peer exchange disabled
      - TERPD_P2P_PEX=false
      # TODO: grab self-contained snapshot or statesync
      - SNAPSHOT_URL=https://server-4.itrocket.net/mainnet/terp/terp_2025-10-01_14190759_snap.tar.lz4
      - SNAPSHOT_FORMAT=tar.lz4
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - STATESYNC_RPC_SERVERS=<https://statesync-a.terp.network:443,https://statesync-b.terp.network:443>
      - ADDRBOOK_URL=https://raw.githubusercontent.com/111STAVR111/props/main/Terp/addrbook.json
      # validator is private peer & unconditional
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=
      - TERPD_P2P_PERSISTENT_PEERS=<>
      - WASMVM_PATH=/lib/libwasmvm.x86_64.so
      - WASMVM_VERSION=v3.0.2
      - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v3.0.2/libwasmvm.x86_64.so
  oline-b-right-node:
    image: ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
    env:
      - MONIKER=terp-node
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - TERPD_P2P_PEX=false
      # TODO: grab self-contained snapshot
      - SNAPSHOT_URL=https://snapshots.nodejumper.io/terp/terp_latest.tar.lz4
      - SNAPSHOT_FORMAT=tar.lz4
      - MINIMUM_GAS_PRICES=0.05uthiol
      # validator private peer 
      - TERPD_P2P_PRIVATE_PEER_IDS=
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=
      - TERPD_P2P_PERSISTENT_PEERS=<>
      - WASMVM_PATH=/lib/libwasmvm.x86_64.so
      - WASMVM_VERSION=v3.0.2
      - WASMVM_URL=https://github.com/CosmWasm/wasmvm/releases/download/v3.0.2/libwasmvm.x86_64.so
profiles:
  compute:
    oline-b-left-node:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
    oline-b-right-node:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
  placement:
    dcloud:
      pricing:
        oline-b-left-node:
          denom: uakt
          amount: 1000
        oline-b-right-node:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  oline-b-left-node:
    dcloud:
      profile: oline-b-left-node
      count: 1
  oline-b-right-node:
    dcloud:
      profile: oline-b-right-node
      count: 1
