---
version: "2.0"
services:
  ${LF_SVC}:
    image: ${OMNIBUS_IMAGE}
    command:
      - sh
    args:
      - -c
      - curl -fsSL ${OLINE_ENTRYPOINT_URL} -o /tmp/wrapper.sh; bash /tmp/wrapper.sh
    expose:
      - port: ${P2P_P_FL}
        as: ${P2P_P_FL}
        to:
          - global: true
      - port: ${RPC_P_FL}
        as: ${RPC_P_FL}
        to:
          - global: true
      - port: ${API_P_FL}
        as: ${API_P_FL}
        to:
          - global: true
      - port: ${GRPC_P_FL}
        as: ${GRPC_P_FL}
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
        accept:
${LF_80_ACCEPTS}
      - port: ${SSH_P}
        as: ${SSH_P}
        to:
          - global: true
    env:
      - OLINE_ENTRYPOINT_URL=${OLINE_ENTRYPOINT_URL}
      - MONIKER=${LEFT_FMONIKER}
      - PROJECT_BIN=${OLINE_BINARY}
      - CHAIN_JSON=${OLINE_CHAIN_JSON}
      - CHAIN_ID=${OLINE_CHAIN_ID}
      - OLINE_OFFLINE=${OLINE_OFFLINE}
      - SNAPSHOT_MODE=${SNAPSHOT_MODE}
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      - TERPD_P2P_SEEDS=${TERPD_P2P_SEEDS}
      - TERPD_P2P_PEX=true
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
      - SNAPSHOT_FORMAT=${OLINE_SNAP_SAVE_FORMAT}
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAP_INTERVAL=500
      - STATESYNC_RPC_SERVERS=${STATESYNC_RPC_SERVERS}
      - STATESYNC_ENABLE=${STATESYNC_ENABLE}
      - STATESYNC_TRUST_HEIGHT=${STATESYNC_TRUST_HEIGHT}
      - STATESYNC_TRUST_HASH=${STATESYNC_TRUST_HASH}
      - STATESYNC_TRUST_PERIOD=${STATESYNC_TRUST_PERIOD}
      - RPC_DOMAIN=${RPC_D_FL}
      - RPC_P=${RPC_P_FL}
      - API_D=${API_D_FL}
      - API_P=${API_P_FL}
      - P2P_D=${P2P_D_FL}
      - P2P_P=${P2P_P_FL}
      - GRPC_P=${GRPC_P_FL}
      - GRPC_D=${GRPC_D_FL}
      - SSH_PUBKEY=${SSH_PUBKEY}
  ${RF_SVC}:
    image: ${OMNIBUS_IMAGE}
    command:
      - sh
    args:
      - -c
      - curl -fsSL ${OLINE_ENTRYPOINT_URL} -o /tmp/wrapper.sh; bash /tmp/wrapper.sh
    expose:
      - port: ${P2P_P_FR}
        as: ${P2P_P_FR}
        to:
          - global: true
      - port: ${RPC_P_FR}
        as: ${RPC_P_FR}
        to:
          - global: true
      - port: ${API_P_FR}
        as: ${API_P_FR}
        to:
          - global: true
      - port: ${GRPC_P_FR}
        as: ${GRPC_P_FR}
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
        accept:
${RF_80_ACCEPTS}
      - port: ${SSH_P}
        as: ${SSH_P}
        to:
          - global: true
    env:
      - OLINE_ENTRYPOINT_URL=${OLINE_ENTRYPOINT_URL}
      - MONIKER=${RIGHT_FMONIKER}
      - PROJECT_BIN=${OLINE_BINARY}
      - CHAIN_JSON=${OLINE_CHAIN_JSON}
      - CHAIN_ID=${OLINE_CHAIN_ID}
      - OLINE_OFFLINE=${OLINE_OFFLINE}
      - SNAPSHOT_MODE=${SNAPSHOT_MODE}
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      - TERPD_P2P_SEEDS=${TERPD_P2P_SEEDS}
      - TERPD_P2P_PEX=true
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
      - SNAPSHOT_FORMAT=${OLINE_SNAP_SAVE_FORMAT}
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAP_INTERVAL=500
      - STATESYNC_RPC_SERVERS=${STATESYNC_RPC_SERVERS}
      - STATESYNC_ENABLE=${STATESYNC_ENABLE}
      - STATESYNC_TRUST_HEIGHT=${STATESYNC_TRUST_HEIGHT}
      - STATESYNC_TRUST_HASH=${STATESYNC_TRUST_HASH}
      - STATESYNC_TRUST_PERIOD=${STATESYNC_TRUST_PERIOD}
      - RPC_DOMAIN=${RPC_D_FR}
      - RPC_P=${RPC_P_FR}
      - API_D=${API_D_FR}
      - API_P=${API_P_FR}
      - P2P_D=${P2P_D_FR}
      - P2P_P=${P2P_P_FR}
      - GRPC_P=${GRPC_P_FR}
      - GRPC_D=${GRPC_D_FR}
      - SSH_PUBKEY=${SSH_PUBKEY}
profiles:
  compute:
    ${LF_SVC}:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
    ${RF_SVC}:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
  placement:
    dcloud:
      pricing:
        ${LF_SVC}:
          denom: uact
          amount: 1000
        ${RF_SVC}:
          denom: uact
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  ${LF_SVC}:
    dcloud:
      profile: ${LF_SVC}
      count: 1
  ${RF_SVC}:
    dcloud:
      profile: ${RF_SVC}
      count: 1
