---
version: "2.0"
services:
  ${VALIDATOR_SVC}:
    image: ${LOCALTERP_IMAGE}
    expose:
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 26657
        as: 26657
        to:
          - global: true
      - port: 5000
        as: 5000
        to:
          - global: true
      - port: 1317
        as: 1317
        to:
          - global: true
      - port: 9090
        as: 9090
        to:
          - global: true
      - port: 5000
        as: 80
        to:
          - global: true
        accept:
${VALIDATOR_80_ACCEPTS}
    env:
      - CHAINID=${TESTNET_CHAIN_ID}
      - FAST_BLOCKS=${TESTNET_FAST_BLOCKS}
  ${SNAPSHOT_SVC}:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: ${P2P_P_SNAP}
        as: ${P2P_P_SNAP}
        to:
          - global: true
      - port: ${RPC_P_SNAP}
        as: ${RPC_P_SNAP}
        to:
          - global: true
      - port: 9091
        as: ${GRPC_P_SNAP}
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
        accept:
${SNAPSHOT_80_ACCEPTS}
      - port: ${SSH_P}
        as: ${SSH_P}
        to:
          - global: true
    env:
      - MONIKER=${SNAPSHOT_MONIKER}
      - PROJECT_BIN=${OLINE_BINARY}
      - CHAIN_ID=${TESTNET_CHAIN_ID}
      - CHAIN_JSON=${OLINE_CHAIN_JSON}
      - OLINE_OFFLINE=1
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - PRUNING=nothing
      - STATESYNC_SNAP_INTERVAL=500
      - TERPD_P2P_PEX=false
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - RPC_DOMAIN=${RPC_D_SNAP}
      - RPC_P=${RPC_P_SNAP}
      - API_D=${API_D_SNAP}
      - API_P=${API_P_SNAP}
      - P2P_D=${P2P_D_SNAP}
      - P2P_P=${P2P_P_SNAP}
      - GRPC_P=${GRPC_P_SNAP}
      - GRPC_D=${GRPC_D_SNAP}
      - SSH_PUBKEY=${SSH_PUBKEY}
  ${SEED_SVC}:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: 26657
        as: 26657
        to:
          - global: true
      - port: 26656
        as: 26656
        to:
          - global: true
      - port: 9091
        as: ${GRPC_P_SEED}
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
        accept:
${SEED_80_ACCEPTS}
      - port: ${SSH_P}
        as: ${SSH_P}
        to:
          - global: true
    env:
      - SSH_PUBKEY=${SSH_PUBKEY}
      - MONIKER=${SEED_MONIKER}
      - PROJECT_BIN=${OLINE_BINARY}
      - CHAIN_ID=${TESTNET_CHAIN_ID}
      - CHAIN_JSON=${OLINE_CHAIN_JSON}
      - OLINE_OFFLINE=1
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      - TERPD_P2P_PEX=true
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAP_INTERVAL=500
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - RPC_DOMAIN=${RPC_D_SEED}
      - RPC_P=${RPC_P_SEED}
      - API_D=${API_D_SEED}
      - API_P=${API_P_SEED}
      - P2P_D=${P2P_D_SEED}
      - P2P_P=${P2P_P_SEED}
      - GRPC_P=${GRPC_P_SEED}
      - GRPC_D=${GRPC_D_SEED}
profiles:
  compute:
    ${VALIDATOR_SVC}:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 10Gi
    ${SNAPSHOT_SVC}:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          - size: 20Gi
    ${SEED_SVC}:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          - size: 20Gi
  placement:
    dcloud:
      pricing:
        ${VALIDATOR_SVC}:
          denom: uact
          amount: 1000
        ${SNAPSHOT_SVC}:
          denom: uact
          amount: 1000
        ${SEED_SVC}:
          denom: uact
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  ${VALIDATOR_SVC}:
    dcloud:
      profile: ${VALIDATOR_SVC}
      count: 1
  ${SNAPSHOT_SVC}:
    dcloud:
      profile: ${SNAPSHOT_SVC}
      count: 1
  ${SEED_SVC}:
    dcloud:
      profile: ${SEED_SVC}
      count: 1
