---
version: "2.0"
services:
  ${LT_SVC}:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: ${P2P_P_TL}
        as: ${P2P_P_TL}
        to:
          - global: true
      - port: ${RPC_P_TL}
        as: ${RPC_P_TL}
        to:
          - global: true
      - port: ${API_P_TL}
        as: ${API_P_TL}
        to:
          - global: true
      - port: ${GRPC_P_TL}
        as: ${GRPC_P_TL}
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
        accept:
${LT_80_ACCEPTS}
      - port: ${SSH_P}
        as: ${SSH_P}
        to:
          - global: true
    env:
      - MONIKER=${LEFT_TACKLE_MONIKER}
      - PROJECT_BIN=${OLINE_BINARY}
      - CHAIN_JSON=${OLINE_CHAIN_JSON}
      - CHAIN_ID=${TESTNET_CHAIN_ID}
      - OLINE_OFFLINE=1
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      - TERPD_P2P_PEX=false
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAP_INTERVAL=500
      - STATESYNC_RPC_SERVERS=${STATESYNC_RPC_SERVERS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - RPC_DOMAIN=${RPC_D_TL}
      - RPC_P=${RPC_P_TL}
      - API_D=${API_D_TL}
      - API_P=${API_P_TL}
      - P2P_D=${P2P_D_TL}
      - P2P_P=${P2P_P_TL}
      - GRPC_P=${GRPC_P_TL}
      - GRPC_D=${GRPC_D_TL}
      - SSH_PUBKEY=${SSH_PUBKEY}
  ${RT_SVC}:
    image: ${OMNIBUS_IMAGE}
    expose:
      - port: ${P2P_P_TR}
        as: ${P2P_P_TR}
        to:
          - global: true
      - port: ${RPC_P_TR}
        as: ${RPC_P_TR}
        to:
          - global: true
      - port: ${API_P_TR}
        as: ${API_P_TR}
        to:
          - global: true
      - port: ${GRPC_P_TR}
        as: ${GRPC_P_TR}
        to:
          - global: true
      - port: 80
        as: 80
        to:
          - global: true
        accept:
${RT_80_ACCEPTS}
      - port: ${SSH_P}
        as: ${SSH_P}
        to:
          - global: true
    env:
      - MONIKER=${RIGHT_TACKLE_MONIKER}
      - PROJECT_BIN=${OLINE_BINARY}
      - CHAIN_JSON=${OLINE_CHAIN_JSON}
      - CHAIN_ID=${TESTNET_CHAIN_ID}
      - OLINE_OFFLINE=1
      - MINIMUM_GAS_PRICES=0.05uthiol
      - PRUNING=default
      - TERPD_P2P_PEX=false
      - FASTSYNC_VERSION=v0
      - STATESYNC_SNAP_INTERVAL=500
      - STATESYNC_RPC_SERVERS=${STATESYNC_RPC_SERVERS}
      - TERPD_P2P_PRIVATE_PEER_IDS=${TERPD_P2P_PRIVATE_PEER_IDS}
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=${TERPD_P2P_UNCONDITIONAL_PEER_IDS}
      - TERPD_P2P_PERSISTENT_PEERS=${TERPD_P2P_PERSISTENT_PEERS}
      - RPC_DOMAIN=${RPC_D_TR}
      - RPC_P=${RPC_P_TR}
      - API_D=${API_D_TR}
      - API_P=${API_P_TR}
      - P2P_D=${P2P_D_TR}
      - P2P_P=${P2P_P_TR}
      - GRPC_P=${GRPC_P_TR}
      - GRPC_D=${GRPC_D_TR}
      - SSH_PUBKEY=${SSH_PUBKEY}
profiles:
  compute:
    ${LT_SVC}:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
    ${RT_SVC}:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          - size: 60Gi
  placement:
    dcloud:
      pricing:
        ${LT_SVC}:
          denom: uact
          amount: 1000
        ${RT_SVC}:
          denom: uact
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  ${LT_SVC}:
    dcloud:
      profile: ${LT_SVC}
      count: 1
  ${RT_SVC}:
    dcloud:
      profile: ${RT_SVC}
      count: 1
