---
version: "2.0"
services:
  sentry:left-tackle:
    image: ghcr.io/akash-network/cosmos-omnibus:v1.2.11-generic
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        as: 80
        to:
          - global: true
    env:
      - MONIKER=public-node-1
      - >-
        CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - PRUNING=nothing
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - ADDRBOOK_URL=https://raw.githubusercontent.com/111STAVR111/props/main/Terp/addrbook.json
      - SNAPSHOT_URL=https://snapshots.nodejumper.io/terp/terp_latest.tar.lz4
  sentry:right-tackle:
    image: ghcr.io/akash-network/cosmos-omnibus:v1.2.11-generic
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        as: 80
        to:
          - global: true
    env:
      - MONIKER=public-node-2
      - >-
        CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - PRUNING=nothing
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - ADDRBOOK_URL=https://raw.githubusercontent.com/111STAVR111/props/main/Terp/addrbook.json
      - SNAPSHOT_URL=https://snapshots.nodejumper.io/terp/terp_latest.tar.lz4
profiles:
  compute:
    sentry:left-tackle:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 100Gi
    sentry:right-tackle:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 100Gi
  placement:
    dcloud:
      pricing:
        sentry:left-tackle:
          denom: uakt
          amount: 1000
        sentry:right-tackle:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash
deployment:
  sentry:left-tackle:
    dcloud:
      profile: sentry:left-tackle
      count: 1
  sentry:right-tackle:
    dcloud:
      profile: sentry:right-tackle
      count: 1
