// @generated by proto-gen. Do not edit.
// Cloudflare proto modules removed — oline uses the cloudflare REST crate
// for DNS/IPFS. Regenerate from openapi specs if needed.

pub mod google {
    pub mod api {
        include!("gen/google.api.rs");
    }
}

pub mod headscale {
    pub mod v1 {
        include!("gen/headscale.v1.rs");
    }
}
