//! Proto compiler for headscale-proto.
//!
//! Auto-discovers .proto files under proto/headscale/, compiles with
//! prost/tonic, generates src/gen/ with Rust types and gRPC client stubs.
//!
//! Run via: `cargo run --manifest-path proto/Cargo.toml --bin proto-gen`

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::fs;

const SERDE_JSON: &str = "#[derive(serde::Serialize, serde::Deserialize)]";

const EXCLUDE_DIRS: &[&str] = &["src", "target", "_unused"];

fn main() -> anyhow::Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    println!("proto root: {}", root.display());

    let target_dir = root.join("src").join("gen");
    fs::create_dir_all(&target_dir)?;
    let target_dir = target_dir.canonicalize()?;
    println!("target_dir: {}", target_dir.display());

    // Auto-discover .proto files (exclude src/, target/)
    let proto_files: Vec<PathBuf> = walkdir::WalkDir::new(&root)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| {
            let path = e.path();
            path.extension().map_or(false, |ext| ext == "proto")
                && !path.components().any(|c| {
                    EXCLUDE_DIRS.iter().any(|excl| c.as_os_str() == *excl)
                })
        })
        .map(|e| e.path().to_path_buf())
        .collect();

    if proto_files.is_empty() {
        anyhow::bail!("No .proto files found under {}", root.display());
    }
    println!("Compiling {} proto file(s):", proto_files.len());
    for f in &proto_files {
        println!("  {}", f.display());
    }

    let include_paths = vec![root.clone()];

    // Compile with prost + tonic
    let mut config = prost_build::Config::new();
    config.extern_path(".google.protobuf", "::pbjson_types");
    config.compile_well_known_types();
    config.type_attribute(".", SERDE_JSON);
    config.out_dir(&target_dir).enable_type_names();

    let rpc_doc_attr = r#"#[cfg(feature = "rpc")]"#;

    tonic_prost_build::configure()
        .out_dir(&target_dir)
        .emit_rerun_if_changed(false)
        .server_mod_attribute(".", rpc_doc_attr)
        .client_mod_attribute(".", rpc_doc_attr)
        .compile_with_config(config, &proto_files, &include_paths)?;

    // Generate JSON serde impls
    pbjson_build::Builder::new()
        .ignore_unknown_fields()
        .out_dir(&target_dir)
        .build(&["."])?;

    // Generate mod.rs from output files
    generate_mod_rs(&target_dir)?;

    println!("Proto generation complete.");
    Ok(())
}

/// Scan generated .rs files and build a nested module tree in mod.rs.
fn generate_mod_rs(dir: &Path) -> anyhow::Result<()> {
    let mut modules: BTreeMap<String, Vec<String>> = BTreeMap::new();

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(true, |ext| ext != "rs") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        if stem == "mod" {
            continue;
        }

        // File names like "headscale.v1.rs" → module path ["headscale", "v1"]
        let parts: Vec<String> = stem.split('.').map(|s| s.to_string()).collect();
        modules.insert(stem, parts);
    }

    let mut mod_content = String::from("// @generated by proto-gen. Do not edit.\n\n");

    // Group by top-level namespace
    let mut tree: BTreeMap<String, Vec<(String, Vec<String>)>> = BTreeMap::new();
    for (file_stem, parts) in &modules {
        let ns = parts[0].clone();
        tree.entry(ns).or_default().push((file_stem.clone(), parts.clone()));
    }

    for (ns, files) in &tree {
        if files.len() == 1 && files[0].1.len() == 1 {
            // Single-level module
            mod_content.push_str(&format!(
                "pub mod {} {{\n    include!(\"gen/{}.rs\");\n}}\n\n",
                ns, files[0].0
            ));
        } else {
            // Nested module
            mod_content.push_str(&format!("pub mod {} {{\n", ns));
            // Group by second level
            let mut sub: BTreeMap<String, Vec<String>> = BTreeMap::new();
            for (file_stem, parts) in files {
                if parts.len() >= 2 {
                    sub.entry(parts[1].clone()).or_default().push(file_stem.clone());
                } else {
                    mod_content.push_str(&format!(
                        "    include!(\"gen/{}.rs\");\n",
                        file_stem
                    ));
                }
            }
            for (sub_ns, file_stems) in &sub {
                mod_content.push_str(&format!("    pub mod {} {{\n", sub_ns));
                for file_stem in file_stems {
                    mod_content.push_str(&format!(
                        "        include!(\"gen/{}.rs\");\n",
                        file_stem
                    ));
                }
                mod_content.push_str("    }\n");
            }
            mod_content.push_str("}\n\n");
        }
    }

    fs::write(dir.parent().unwrap().join("lib.rs"), &mod_content)?;
    println!("Generated lib.rs with {} module(s)", tree.len());
    Ok(())
}
