---
version: "2.0"

services:
  validator:
    image:  ghcr.io/permissionlessweb/o-line:v0.0.4-terpnetwork-v4.2.2
    env:
      - MONIKER=validator
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - TERP_P2P_PEX=false
      - TERP_P2P_UNCONDITIONAL_PEER_IDS=<node-1-id>,<node-2-id>...
      - TERP_P2P_ADDR_BOOK_STRICT=false
      - TERP_CONSENSUS_DOUBLE_SIGN_CHECK_HEIGHT=10
      - P2P_PERSISTENT_PEERS=<id@node1:port,id@node2:port>
      - STATESYNC_RPC_SERVERS=<node1:80>,<node2:80>
      - S3_KEY=<s3-key>
      - S3_SECRET=<s3-secret>
      - KEY_PASSWORD=<key password>
      - KEY_PATH=<bucket/validator>
    expose:
      - port: 26657
        as: 80
        to:
          - global: true # debug
        accept:
        - rpc.permissionless.money
        - www.rpc.permissionless.money
      - port: 26656
        as: 80
        to:
          - global: true # debug
        accept:
        - peer.permissionless.money
        - seed.permissionless.money
      - port: 1317
        as: 80
        to:
          - global: true # debug
        accept:
        - api.permissionless.money
        - www.api.permissionless.money
    # params:
    #   storage:
    #     data:
    #       mount: /root/.akash

profiles:
  compute:
    validator:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        validator:
          denom: uakt
          amount: 1000

deployment:
  validator:
    dcloud:
      profile: validator
      count: 1
