---
version: "2.0"

services:
  # validator:
  #   image:  ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
  #   env:
  #     - MONIKER=validator
  #     - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
  #     - MINIMUM_GAS_PRICES=0.05uthiol
  #     - FASTSYNC_VERSION=v0
  #     - TERPD_P2P_PEX=false
  #     - TERPD_P2P_UNCONDITIONAL_PEER_IDS=<node-1-id>,<node-2-id>...
  #     - TERPD_P2P_ADDR_BOOK_STRICT=false
  #     - TERP_CONSENSUS_DOUBLE_SIGN_CHECK_HEIGHT=10
  #     - P2P_PERSISTENT_PEERS=<id@node1:port,id@node2:port>
  #     - STATESYNC_RPC_SERVERS=<node1:80>,<node2:80>
  #   depends_on:
  #     - service: node1
  #     - service: node2
  #   expose:
  #     - port: 26657
  #       as: 80
  #       to:
  #         - service: node1
  #         - service: node2
  #         - global: true # debug
  #     - port: 26656
  #       to:
  #         - service: node1
  #         - service: node2
  #   # params:
  #   #   storage:
  #   #     data:
  #   #       mount: /root/.akash
  node1:
    image:  ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
    env:
      - MONIKER=private_node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - TERPD_P2P_PEX=true
      - TERPD_P2P_PRIVATE_PEER_IDS=
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=
      - TERPD_P2P_ADDR_BOOK_STRICT=false
      - ADDRBOOK_URL=https://raw.githubusercontent.com/111STAVR111/props/main/Terp/addrbook.json
      - SNAPSHOT_URL=https://snapshots.nodejumper.io/terp/terp_latest.tar.lz4
      - STATESYNC_SNAPSHOT_INTERVAL=500
      - 

    expose:
      - port: 26657
        as: 80
        to:
          - service: validator
          - global: true # debug
      - port: 26656
        to:
          - service: validator
    # params:
    #   storage:
    #     data:
    #       mount: /root/.akash
  node2:
    image:  ghcr.io/akash-network/cosmos-omnibus:v1.2.28-generic
    env:
      - MONIKER=private_node_2
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/refs/heads/master/terpnetwork/chain.json
      - MINIMUM_GAS_PRICES=0.05uthiol
      - FASTSYNC_VERSION=v0
      - TERPD_P2P_PEX=true
      - TERPD_P2P_PRIVATE_PEER_IDS=<validatorid>
      - TERPD_P2P_UNCONDITIONAL_PEER_IDS=<validatorid>
      - TERPD_P2P_ADDR_BOOK_STRICT=false
      - STATESYNC_RPC_SERVERS=<publicnode1:26657,publicnode2:26657>
      - STATESYNC_SNAPSHOT_INTERVAL=500
    expose:
      - port: 26657
        as: 80
        to:
          - service: validator
          - global: true # debug
      - port: 26656
        to:
          - service: validator
    # params:
    #   storage:
    #     data:
    #       mount: /root/.akash

profiles:
  compute:
    validator:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
    node1:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
    node2:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 100Gi
          # - size: 100Mi
          # - name: data
          #   size: 400Gi
          #   attributes:
          #     persistent: true
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        validator:
          denom: uakt
          amount: 1000
        node1:
          denom: uakt
          amount: 1000
        node2:
          denom: uakt
          amount: 1000

deployment:
  validator:
    dcloud:
      profile: validator
      count: 1
  node1:
    dcloud:
      profile: node1
      count: 1
  node2:
    dcloud:
      profile: node2
      count: 1
